// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xtrybmrqgvzutrgsywvf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh0cnlibXJxZ3Z6dXRyZ3N5d3ZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAwNjA3MzksImV4cCI6MjA4NTYzNjczOX0.o1ChHcnjFrQkNAQXfTlXV12K-DoWaqZ3dxa7PHv7k9s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});